del /F /Q widevinecdmadapter.dll
del /F /Q libGLESv2.dll
del /F /Q libEGL.dll
del /F /Q d3dcompiler_47.dll
del /F /Q CefSharp.Core.pdb
del /F /Q TouchBrowser.pdb
del /F /Q TouchBrowser.vshost.exe.manifest
del /F /Q CefSharp.Wpf.dll
del /F /Q CefSharp.Wpf.pdb
del /F /Q CefSharp.Wpf.xml
del /F /Q CefSharp.WinForms.pdb
del /F /Q CefSharp.pdb
del /F /Q CefSharp.BrowserSubprocess.Core.pdb
del /F /Q CefSharp.BrowserSubprocess.pdb
del /F /Q TouchBrowser.vshost.exe
del /F /Q TouchBrowser.vshost.exe.config
del /F /Q TouchBrowser.exe.config
del /F /Q Clean.bat